// npm install stylelint postcss@^8 stylelint-config-html postcss-html postcss-scss postcss-less stylelint-webpack-plugin -D

// stylelint src/**/*.{vue,html,scss,css} --fix

// configureWebpack
// const StylelintPlugin = require('stylelint-webpack-plugin')
// new StylelintPlugin({
//   files: 'src/**/*.{html,vue,css,scss}',
//   fix: false,
//   cache: true,
//   failOnError: true
// })


module.exports = {
  root: true,
  overrides: [
    {
      files: ["**/*.vue", "**/*.html"],
      extends: ["stylelint-config-html"]
    },
    {
      files: ["**/*.less"],
      customSyntax: 'postcss-less'
    },
    {
      files: ["**/*.scss"],
      customSyntax: 'postcss-scss'
    }
  ],
  rules: {
    // "at-rule-blacklist": null,
    "at-rule-empty-line-before": "never",
    // "at-rule-name-case": "lower",
    // "at-rule-name-newline-after": "always-multi-line",
    "at-rule-name-space-after": "always",
    // "at-rule-no-unknown": null,
    "at-rule-no-vendor-prefix": true,
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "never",
    // "at-rule-whitelist": null,
    "block-closing-brace-empty-line-before": "never",
    "block-closing-brace-newline-after": "always-multi-line",
    "block-closing-brace-newline-before": "always",
    "block-closing-brace-space-after": "always-single-line",
    "block-closing-brace-space-before": "always-single-line",
    "block-no-empty": true,
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-newline-before": null,
    "block-opening-brace-space-after": "always-single-line",
    "block-opening-brace-space-before": "always",
    // "color-hex-case": "lower",
    "color-hex-length": "short",
    // "color-named": null,
    // "color-no-hex": null,
    "color-no-invalid-hex": true,
    // "comment-empty-line-before": null,
    // "comment-no-empty": null,
    // "comment-whitespace-inside": null,
    // "comment-word-blacklist": null,
    // "custom-media-pattern": null,
    // "custom-property-empty-line-before": null,
    // "custom-property-pattern": null,
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    // "declaration-block-no-duplicate-properties": null,
    // "declaration-block-no-redundant-longhand-properties": null,
    // "declaration-block-no-shorthand-property-overrides": null,
    "declaration-block-semicolon-newline-after": "always-multi-line",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never",
    // "declaration-block-single-line-max-declarations": null,
    "declaration-block-trailing-semicolon": "always",
    // "declaration-colon-newline-after": null,
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-empty-line-before": "never",
    // "declaration-no-important": null,
    // "declaration-property-unit-blacklist": null,
    // "declaration-property-unit-whitelist": null,
    // "declaration-property-value-blacklist": null,
    // "declaration-property-value-whitelist": null,
    // "font-family-name-quotes": null,
    "font-family-no-duplicate-names": true,
    // "font-family-no-missing-generic-family-keyword": null,
    // "font-weight-notation": null,
    // "function-blacklist": null,
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "never-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    // "function-max-empty-lines": null,
    // "function-name-case": null,
    "function-parentheses-newline-inside": "never-multi-line",
    "function-parentheses-space-inside": "never",
    // "function-url-no-scheme-relative": null,
    // "function-url-quotes": null,
    // "function-url-scheme-blacklist": null,
    // "function-url-scheme-whitelist": null,
    // "function-whitelist": null,
    "function-whitespace-after": "always",
    "indentation": 2,
    // "keyframe-declaration-no-important": null,
    // "keyframes-name-pattern": null,
    // "length-zero-no-unit": null,
    // "linebreaks": null,
    "max-empty-lines": 1,
    // "max-line-length": null,
    // "max-nesting-depth": null,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    // "media-feature-name-blacklist": null,
    // "media-feature-name-case": null,
    // "media-feature-name-no-unknown": null,
    // "media-feature-name-no-vendor-prefix": null,
    // "media-feature-name-value-whitelist": null,
    // "media-feature-name-whitelist": null,
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "never-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always",
    "media-query-list-comma-space-before": "never",
    // "no-descending-specificity": null,
    "no-duplicate-at-import-rules": true,
    // "no-duplicate-selectors": null,
    // "no-empty-source": null,
    "no-empty-first-line": true,
    "no-eol-whitespace": true,
    "no-extra-semicolons": true,
    // "no-invalid-double-slash-comments": null,
    // "no-missing-end-of-source-newline": null,
    // "no-unknown-animations": null,
    // "number-leading-zero": null,
    // "number-max-precision": null,
    "number-no-trailing-zeros": true,
    // "property-blacklist": null,
    // "property-case": "lower",
    // "property-no-unknown": true,
    // "property-no-vendor-prefix": null,
    // "property-whitelist": null,
    "rule-empty-line-before": [
      "always",
      {
        except: ["after-single-line-comment", "first-nested"]
      }
    ],
    "selector-attribute-brackets-space-inside": "never",
    // "selector-attribute-operator-blacklist": null,
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    // "selector-attribute-operator-whitelist": null,
    "selector-attribute-quotes": "always",
    // "selector-class-pattern": null,
    // "selector-combinator-blacklist": null,
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    // "selector-combinator-whitelist": null,
    "selector-descendant-combinator-no-non-space": true,
    // "selector-id-pattern": null,
    "selector-list-comma-newline-after": "never-multi-line",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always",
    "selector-list-comma-space-before": "never",
    // "selector-max-attribute": null,
    // "selector-max-class": null,
    // "selector-max-combinators": null,
    // "selector-max-compound-selectors": null,
    "selector-max-empty-lines": 0,
    // "selector-max-id": null,
    // "selector-max-pseudo-class": null,
    // "selector-max-specificity": null,
    // "selector-max-type": null,
    // "selector-max-universal": null,
    // "selector-nested-pattern": null,
    // "selector-no-qualifying-type": null,
    // "selector-no-vendor-prefix": null,
    // "selector-pseudo-class-blacklist": null,
    // "selector-pseudo-class-case": "lower",
    // "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-class-parentheses-space-inside": "never",
    // "selector-pseudo-class-whitelist": null,
    // "selector-pseudo-element-blacklist": null,
    // "selector-pseudo-element-case": "lower",
    // "selector-pseudo-element-colon-notation": null,
    "selector-pseudo-element-no-unknown": true,
    // "selector-pseudo-element-whitelist": null,
    // "selector-type-case": "lower",
    "selector-type-no-unknown": true,
    // "shorthand-property-no-redundant-values": null,
    "string-no-newline": true,
    "string-quotes": "double",
    // "time-min-milliseconds": null,
    // "unit-blacklist": null,
    // "unit-case": null,
    // "unit-no-unknown": null,
    // "unit-whitelist": null,
    // "value-keyword-case": "lower",
    "value-list-comma-newline-after": "never-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always",
    "value-list-comma-space-before": "never",
    "value-list-max-empty-lines": 0,
    // "value-no-vendor-prefix": null
  }
}
